name: Deploy to Gigalixir

on: [workflow_call]

jobs:
  deploy:
    environment: gigalixir
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Repo
        env:
          GIGALIXIR_EMAIL: ${{ vars.GIGALIXIR_EMAIL_VAR }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP_NAME: ${{ vars.GIGALIXIR_APP_NAME_VAR }}
        run: |
          echo "api_length:(${#GIGALIXIR_API_KEY})"
          echo "email_length:(${#GIGALIXIR_EMAIL})"
          git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
      - name: Deploy to Gigalixir
        run: git push -f gigalixir master