name: Deploy to Gigalixir

on: [workflow_call]

jobs:
  deploy_blocker:
    environment: gigalixir
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Gigalixir"
  deploy:
    runs-on: ubuntu-latest
    needs: deploy_blocker
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Repo
        run: |
          git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
        env:
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}
      - name: Deploy to Gigalixir
        run: git push -f gigalixir master