name: Deploy to Gigalixir

on: [workflow_call]

jobs:
  deploy_blocker:
    environment: gigalixir
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Gigalixir"
  deploy:
    runs-on: ubuntu-latest
    needs: deploy_blocker
    steps:
      - name: Deploy to Gigalixir
        run: git push gigalixir master
