name: Master
run-name: Master

on: 
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
  deploy:
    name: Deploy
    secrets: inherit
    needs: test
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yaml

